[package]
edition = "2021"
license = { workspace = true }
name = "buck2_subscription_proto"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
allocative = { workspace = true }
derive_more = { workspace = true }
prost = { workspace = true }
serde = { workspace = true }
tonic = { workspace = true }

[build-dependencies]
buck2_protoc_dev = { workspace = true }
