[package]
authors = ["Facebook"]
description = "Derive macros for the Buck's buck2_build_api"
edition = "2021"
license = { workspace = true }
name = "buck2_build_api_derive"
repository = { workspace = true }
version = "0.4.1"

[lib]
proc-macro = true

[dependencies]
convert_case = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }

gazebo = { workspace = true }
