[package]
edition = "2021"
license = { workspace = true }
name = "buck2_data"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
allocative = { workspace = true }
derive_more = { workspace = true }
hex = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
serde = { workspace = true }
tonic = { workspace = true }

dupe = { workspace = true }
gazebo = { workspace = true }

[build-dependencies]
buck2_protoc_dev = { workspace = true }
