[package]
edition = "2021"
license = { workspace = true }
name = "buck2_test_runner"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
parking_lot = { workspace = true }
tokio = { workspace = true }

buck2_error = { workspace = true }
buck2_grpc = { workspace = true }
buck2_test_api = { workspace = true }
host_sharing = { workspace = true }
