[package]
authors = ["Meta"]
description = "Serialized datastructures for buck2_miniperf"
edition = "2021"
license = { workspace = true }
name = "buck2_miniperf_proto"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
buck2_data = { workspace = true }
dupe = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
bincode = { workspace = true }
