[package]
authors = ["Meta"]
description = "Eden integration for Buck2"
edition = "2021"
license = { workspace = true }
name = "buck2_eden"
repository = { workspace = true }
version = "0.1.0"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(fbcode_build)"] }
