[package]
authors = ["Facebook"]
description = "Proc macros for Buck's buck_query crate"
edition = "2021"
license = { workspace = true }
name = "buck2_query_derive"
repository = { workspace = true }
version = "0.4.1"

[lib]
proc-macro = true

[dependencies]
itertools = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
textwrap = { workspace = true }
