[package]
description = "Data structure"
edition = "2021"
license = { workspace = true }
name = "lock_free_vec"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
allocative = { workspace = true }
