[package]
authors = ["Meta"]
description = "Run 3B instructions"
edition = "2021"
license = { workspace = true }
name = "three_billion_instructions"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
thiserror = { workspace = true }
