name: Build and test
on:
  push:
  pull_request:
  workflow_dispatch: # allows manual triggering
jobs:
  linux-build-and-test:
    runs-on: 4-core-ubuntu
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: ./.github/actions/setup_linux_env
    - uses: ./.github/actions/build_debug
    - uses: ./.github/actions/run_test_py
  linux-build-examples:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: ./.github/actions/setup_linux_env
    - uses: ./.github/actions/init_opam
    - uses: ./.github/actions/build_release
    - name: Setup the 'example/with_prelude' project
      run: |-
        cd examples/with_prelude
        ./haskell-setup.sh
        ./ocaml-setup.sh
    - name: Build the 'example/with_prelude' project
      run: |-
        cd examples/with_prelude
        $RUNNER_TEMP/artifacts/buck2 build //... -v 2
        $RUNNER_TEMP/artifacts/buck2 test //... -v 2
    - uses: ./.github/actions/build_example_conan
    - uses: ./.github/actions/build_example_no_prelude
    - uses: ./.github/actions/setup_reindeer
    - uses: ./.github/actions/build_bootstrap
